### ISSUE TITLE
some error , i am in : win7,64.bit, How can i fix it

### ISSUE THREAD

**Issue by buzai** [JJK801/node-shairport-sync#1]
C:\Users\Administrator\Desktop\airplay>node app.js
C:\Users\Administrator\Desktop\airplay\app.js:1
(function (exports, require, module, __filename, __dirname) { import {ShairportS
ync, Stdout} from 'shairport-sync'; // https://www.npmjs.com/package/shairport-s
ync
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by ChristianOrgs** [comment]
Well your node dont recognize import obviously ! Try this instead(works like a charm in my case):

```
const air = require('shairport-sync');
var Speaker = require('speaker');
const output = new air.Stdout();

var speaker = new Speaker({
  channels:   2,
  bitDepth:   16,
  sampleRate: 44100,
  signed: true
})
const airplay = new air.ShairportSync(output);
airplay.name = 'MyAirplay';
airplay.start();
airplay.output.stream.pipe(speaker);
```

**Comment by buzai** [comment]
@ChristianOrgs yes! u are right.
